### ISSUE TITLE
解压assests_sample里的文件显示(file) Is not archive

### ISSUE THREAD

**Issue by LiXDL** [SwedishDoveCooker/nonebot-plugin-weiweibot#2]
![image](https://github.com/user-attachments/assets/09934d83-d36f-491e-ac20-013a8a19d91b)
如图。
我确实是都下了，应该没理解错分卷压缩吧；还试了下从z01解压，也不行，求指导

**Comment by SwedishDoveCooker** [comment]
文件没有问题,如果实在无法下载请走
https://mega.nz/file/nGp3RJqI#cXVv5yJ1FVxTXxr-4W6I4j107J9hFwn6qphMKoLPxcg
